In [1]:
import torch

In [3]:
revenue=torch.tensor([100,120,99,79])
revenue[:3]

tensor([100, 120,  99])

In [4]:
q1=torch.tensor([
    [200,220,250],#iphone
    [150,100,210],
    [300,230,360]
])
q2=torch.tensor([
    [220,320,150],
    [250,300,110],
    [350,130,260]
])

In [6]:
q1+q2

tensor([[420, 540, 400],
        [400, 400, 320],
        [650, 360, 620]])

In [8]:
abs(q1-q2)

tensor([[ 20, 100, 100],
        [100, 200, 100],
        [ 50, 100, 100]])

In [9]:
q1*0.1

tensor([[20., 22., 25.],
        [15., 10., 21.],
        [30., 23., 36.]])

In [10]:
profit=torch.tensor([
    [30,27,25],
    [20,18,17],
    [45,38,25]
])
profit*q1

tensor([[ 6000,  5940,  6250],
        [ 3000,  1800,  3570],
        [13500,  8740,  9000]])

In [16]:
product_prices=torch.tensor([[1100,450,1500]])
product_prices*q1

tensor([[220000,  99000, 375000],
        [165000,  45000, 315000],
        [330000, 103500, 540000]])

In [17]:
torch.matmul(product_prices,q1)

tensor([[737500, 632000, 909500]])

In [18]:
product_prices.t()

tensor([[1100],
        [ 450],
        [1500]])

In [28]:
price_by_region=q1*product_prices.t()
price_by_region

tensor([[220000, 242000, 275000],
        [ 67500,  45000,  94500],
        [450000, 345000, 540000]])

In [29]:
price_by_region.sum(dim=0)

tensor([737500, 632000, 909500])

In [30]:
portfolio_composition = torch.tensor([
    [100.0, 50.0, 30.0],  # P1
    [80.0, 70.0, 20.0],   # P2
    [60.0, 40.0, 90.0]    # P3
], dtype=torch.float32)

# Create price change matrix (3x3)
# Rows: Assets (Stocks, Bonds, Real Estate)
# Columns: Economic scenarios (Growth, Neutral, Recession)
price_changes = torch.tensor([
    [1.15, 1.05, 0.85],  # Stocks
    [1.05, 1.02, 1.10],  # Bonds
    [1.10, 1.00, 0.90]   # Real Estate
], dtype=torch.float32)

values = torch.matmul(portfolio_composition, price_changes)
values 

tensor([[200.5000, 186.0000, 167.0000],
        [187.5000, 175.4000, 163.0000],
        [210.0000, 193.8000, 176.0000]])

In [32]:
83*values

tensor([[16641.5000, 15438.0000, 13861.0000],
        [15562.5000, 14558.1992, 13529.0000],
        [17430.0000, 16085.3994, 14608.0000]])

In [33]:
units=torch.tensor([
    [200,220],
    [150,180],
    [300,330]
])

In [34]:
units.shape

torch.Size([3, 2])

In [35]:
units.dtype

torch.int64

In [36]:
units.device

device(type='cpu')

In [38]:
units.view(-1,)

tensor([200, 220, 150, 180, 300, 330])

In [39]:
units.view(2,3)

tensor([[200, 220, 150],
        [180, 300, 330]])

In [42]:
units[2,1]=331

In [43]:
units

tensor([[200, 220],
        [150, 180],
        [300, 331]])

In [44]:
torch.rand(3,4)

tensor([[0.5927, 0.0832, 0.4519, 0.4038],
        [0.8782, 0.9732, 0.6475, 0.5538],
        [0.4126, 0.5061, 0.3656, 0.8546]])